
// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use diesel::{prelude::Insertable, AsChangeset, Queryable};

use chrono::{DateTime, NaiveDateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::db::schema::account;
//#[derive(Queryable, Debug, Serialize)]

#[derive(Queryable, Debug, Serialize)]
#[diesel(primary_key(id, privatekey))]
pub struct Account {
    pub id: i32,
    pub name: String,
    pub privatekey: String,
    #[serde(skip_serializing)]
    pub phrase: Option<String>,
    pub create_time: DateTime<Utc>,
    pub modify_time: DateTime<Utc>,
    pub create_ip: String,
    #[serde(skip_serializing)]
    pub login_time: Option<DateTime<Utc>>,
    #[serde(skip_serializing)]
    pub login_ip: Option<String>,
}

#[derive( Debug, Serialize,Insertable,Clone)]
#[diesel(table_name=account)]
pub struct CreateAccount {
    pub name: String,
    pub privatekey: String,
    pub phrase: Option<String>,
    pub create_time: DateTime<Utc>,
    pub modify_time: DateTime<Utc>,
    pub create_ip: String,
    //pub login_time: Option<DateTime<Utc>>
    
}

#[derive( Debug,Serialize,Clone,Queryable,Insertable)]
#[diesel(table_name=account)]
pub struct UpdateLoginDb {
    pub name: String,
    pub privatekey: String,
    #[serde(skip_serializing)]
    pub login_time: Option<DateTime<Utc>>,
    #[serde(skip_serializing)]
    pub login_ip: Option<String>,
}
