[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_service = "8kVRtF6vR8fD9yjhVRftCAVJ5W25XjRQ8E8ko6HN5wBJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
