refresh_rate: 1 seconds
appenders:
  log_file:
    kind: rolling_file
    path: "logs/log{}.log"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10mb
      roller:
        kind: fixed_window
        base: 1
        count: 100
        pattern: "-{}"
  stdout:
    kind: console
    encoder:
      kind: pattern
      pattern: "{h({d(%H:%M:%S)})} - {m}{n}"

root:
  level: info
  appenders:
    - stdout
    - log_file
